# Generated by Django 3.1 on 2020-08-10 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Location', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Name of Location', max_length=64, verbose_name='Location Name')),
            ],
            options={
                'verbose_name_plural': 'Job Locations',
            },
        ),
        migrations.AlterModelOptions(
            name='ndecertificate',
            options={'verbose_name_plural': 'NDE Certificates'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('r', 'Ready'), ('e', 'Expired'), ('w', 'Expiring')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_allocation',
            field=models.ForeignKey(help_text='Item Allocated to which project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.joblocation'),
        ),
    ]
