# Generated by Django 3.1 on 2020-08-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200810_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_remarks',
            field=models.CharField(help_text='Additional Comments', max_length=255, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('w', 'Expiring'), ('n', 'Not Ready'), ('r', 'Ready'), ('e', 'Expired')], default='n', help_text='Status of Item', max_length=1),
        ),
    ]
