# Generated by Django 3.1 on 2020-08-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200810_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndecertificate',
            name='validity',
            field=models.NullBooleanField(default=True, verbose_name='Certificate Validity'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_remarks',
            field=models.CharField(blank=True, help_text='Additional Comments', max_length=255, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('r', 'Ready'), ('w', 'Expiring'), ('e', 'Expired')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='ndecertificate',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N'),
        ),
    ]
