# Generated by Django 3.1 on 2020-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200810_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndecertificate',
            options={'verbose_name': 'NDE Certificate', 'verbose_name_plural': 'NDE Certificates'},
        ),
        migrations.AddField(
            model_name='ndecertificate',
            name='in_use',
            field=models.BooleanField(default=True, help_text='Is the certificate in use?', verbose_name='Certificate In Use'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('w', 'Expiring'), ('n', 'Not Ready'), ('r', 'Ready'), ('e', 'Expired')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='ndecertificate',
            name='validity',
            field=models.BooleanField(default=True, help_text='Is the certificate valid?', verbose_name='Certificate Valid'),
        ),
    ]
