# Generated by Django 3.1 on 2020-08-10 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200810_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
            ],
            options={
                'verbose_name': 'Inspection',
            },
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('r', 'Ready'), ('e', 'Expired'), ('w', 'Expiring'), ('n', 'Not Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.DeleteModel(
            name='NDECertificate',
        ),
        migrations.AddField(
            model_name='inspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N'),
        ),
    ]
