# Generated by Django 3.1 on 2020-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200810_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('w', 'Expiring'), ('n', 'Not Ready'), ('e', 'Expired'), ('r', 'Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
