# Generated by Django 3.1 on 2020-08-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200810_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspection',
            new_name='VisualInspection',
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Material Categories'},
        ),
        migrations.AlterModelOptions(
            name='visualinspection',
            options={'verbose_name': 'Visual Inspections'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_allocation',
            field=models.ForeignKey(blank=True, help_text='Item Allocated to which project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.joblocation'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('w', 'Expiring'), ('r', 'Ready'), ('e', 'Expired')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='description',
            field=models.CharField(help_text='Category of Equipment', max_length=64, verbose_name='Description'),
        ),
    ]
