# Generated by Django 3.1 on 2020-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200810_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('r', 'Ready'), ('n', 'Not Ready'), ('e', 'Expired'), ('w', 'Expiring')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.DeleteModel(
            name='VisualInspection',
        ),
    ]
