# Generated by Django 3.0.7 on 2020-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200811_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeworkinstance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('e', 'Expired'), ('r', 'Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='skidinstance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('e', 'Expired'), ('r', 'Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='slinginstance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('e', 'Expired'), ('r', 'Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
        migrations.AlterField(
            model_name='tmmdeinstance',
            name='status',
            field=models.CharField(choices=[('n', 'Not Ready'), ('e', 'Expired'), ('r', 'Ready')], default='n', help_text='Status of Item', max_length=1),
        ),
    ]
