# Generated by Django 3.1 on 2020-08-10 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200810_2346'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePostJobInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N')),
            ],
            options={
                'verbose_name': 'Pipework Pre-Post Inspection',
            },
        ),
        migrations.CreateModel(
            name='PipeworkNDEInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N')),
            ],
            options={
                'verbose_name': 'Pipework NDE Inspection',
            },
        ),
        migrations.CreateModel(
            name='MajorInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N')),
            ],
            options={
                'verbose_name': 'Pipework COC Maintenance',
            },
        ),
        migrations.CreateModel(
            name='AnnualInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instance', verbose_name='Instance S/N')),
            ],
            options={
                'verbose_name': 'Pipework Annual Maintenance',
            },
        ),
    ]
