# Generated by Django 3.1 on 2020-08-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200811_2156'),
        ('inspection', '0003_auto_20200811_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualinspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pipeworkinstance'),
        ),
        migrations.AddField(
            model_name='calibrationinspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tmmdeinstance'),
        ),
        migrations.AddField(
            model_name='majorinspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pipeworkinstance'),
        ),
        migrations.AddField(
            model_name='pipeworkndeinspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pipeworkinstance'),
        ),
        migrations.AddField(
            model_name='prepostjobinspection',
            name='material_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pipeworkinstance'),
        ),
    ]
