# Generated by Django 3.0.7 on 2020-08-11 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200811_2259'),
        ('inspection', '0004_auto_20200811_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkidMPIInpection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SkidInstance')),
            ],
            options={
                'verbose_name': 'Skid MPI Inspection',
                'verbose_name_plural': 'Skid MPI Inspections',
            },
        ),
        migrations.CreateModel(
            name='SkidVisualInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SkidInstance')),
            ],
            options={
                'verbose_name': 'Skid Visual Inspection',
                'verbose_name_plural': 'Skid Visual Inspections',
            },
        ),
        migrations.CreateModel(
            name='SlingMPIInpection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SlingInstance')),
            ],
            options={
                'verbose_name': 'Sling MPI Inspection',
                'verbose_name_plural': 'Sling MPI Inspections',
            },
        ),
        migrations.CreateModel(
            name='SlingVisualInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Material Instance', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('validity_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('validity_end_date', models.DateField(null=True, verbose_name='Expiry Date')),
                ('validity', models.BooleanField(default=True, help_text='Is the inspection valid?', verbose_name='Inspection Valid')),
                ('in_use', models.BooleanField(default=True, help_text='Is the inspection in use?', verbose_name='Inspection In Use')),
                ('material_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SlingInstance')),
            ],
            options={
                'verbose_name': 'Sling Visual Inspection',
                'verbose_name_plural': 'Sling Visual Inspections',
            },
        ),
        migrations.DeleteModel(
            name='MPIInpection',
        ),
        migrations.DeleteModel(
            name='VisualInspection',
        ),
    ]
